### ISSUE TITLE
Failed to determine modification time of model on Azure Storage when starting up triton server after update to release 21.04 

### ISSUE THREAD

**Issue by tony-asus** [triton-inference-server/server#2966]
**Description**
I put triton model repository on my Azure storage account: "--model-repository=as://container/path/to/model". And when trito server starts up, it shows some errors on top:

I0605 15:18:26.273583 1 metrics.cc:228] Collecting metrics for GPU 0: Tesla T4
I0605 15:18:29.035544 1 libtorch.cc:932] TRITONBACKEND_Initialize: pytorch
I0605 15:18:29.035594 1 libtorch.cc:942] Triton TRITONBACKEND API version: 1.0
I0605 15:18:29.035599 1 libtorch.cc:948] 'pytorch' TRITONBACKEND API version: 1.0
2021-06-05 15:18:30.134045: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I0605 15:18:31.265063 1 tensorflow.cc:2165] TRITONBACKEND_Initialize: tensorflow
I0605 15:18:31.265094 1 tensorflow.cc:2175] Triton TRITONBACKEND API version: 1.0
I0605 15:18:31.265098 1 tensorflow.cc:2181] 'tensorflow' TRITONBACKEND API version: 1.0
I0605 15:18:31.265101 1 tensorflow.cc:2205] backend configuration:
{}
I0605 15:18:31.419452 1 onnxruntime.cc:1828] TRITONBACKEND_Initialize: onnxruntime
I0605 15:18:31.419492 1 onnxruntime.cc:1838] Triton TRITONBACKEND API version: 1.0
I0605 15:18:31.419496 1 onnxruntime.cc:1844] 'onnxruntime' TRITONBACKEND API version: 1.0
I0605 15:18:31.681421 1 openvino.cc:1168] TRITONBACKEND_Initialize: openvino
I0605 15:18:31.681451 1 openvino.cc:1178] Triton TRITONBACKEND API version: 1.0
I0605 15:18:31.681456 1 openvino.cc:1184] 'openvino' TRITONBACKEND API version: 1.0
I0605 15:18:31.955195 1 pinned_memory_manager.cc:206] Pinned memory pool is created at '0x7f9700000000' with size 268435456
I0605 15:18:31.960663 1 cuda_memory_manager.cc:103] CUDA memory pool is created on device 0 with size 67108864
E0605 15:18:32.583878 1 model_repository_manager.cc:286] **Failed to determine modification time for 'as://tonytesttritonaccount/tony-model-repository/some_model': Internal: Unable to get blob property for file at as://tonytesttritonaccount/tony-model-repository/some_model**

Later when I wanted to reload model, it showed this error again, and had 8 secs downtime.

I0605 04:55:36.372867 1 model_repository_manager.cc:1099] unloading: some_model:1
I0605 04:55:36.373008 1 libtorch.cc:1055] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0605 04:55:36.382971 1 libtorch.cc:1004] TRITONBACKEND_ModelFinalize: delete model state
I0605 04:55:36.386443 1 model_repository_manager.cc:1223] successfully unloaded 'some_model' version 1
E0605 04:55:44.107722 1 model_repository_manager.cc:298] **Failed to determine modification time for 'as://tonytesttritonaccount/tony-model-repository/some_model': Internal: Unable to get blob property for file at as://tonytesttritonaccount/tony-model-repository/some_model**
I0605 04:55:44.262102 1 model_repository_manager.cc:1066] loading: some_model:1
I0605 04:55:45.522576 1 libtorch.cc:981] TRITONBACKEND_ModelInitialize: some_model (version 1)
W0605 04:55:45.522943 1 libtorch.cc:173] skipping model configuration auto-complete for 'some_model': not supported for pytorch backend
I0605 04:55:45.523439 1 libtorch.cc:1022] TRITONBACKEND_ModelInstanceInitialize: some_model (device 0)
I0605 04:55:45.775833 1 model_repository_manager.cc:1240] successfully loaded 'some_model' version 1

**Triton Information**
What version of Triton are you using?
nvcr.io/nvidia/tritonserver:21.04-py3 or nvcr.io/nvidia/tritonserver:21.05-py3

when I was using nvcr.io/nvidia/tritonserver:21.03-py3, didn't show this error.

Are you using the Triton container or did you build it yourself?
container

**To Reproduce**
Steps to reproduce the behavior.
1. triton model repository was put on azure storage
2. Run triton deployment on AKS using nvcr.io/nvidia/tritonserver:21.04-py3 image with arguments: --model-control-mode=explicit --load-model=some_model --model-repository=as://tonytesttritonaccount/tony-model-repository/
3. kubectl logs -f triton-inference-server-xxxx

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

name: "some_model"
platform: "pytorch_libtorch"
max_batch_size: 10
input [
  {
    name: "input__0"
    data_type: TYPE_INT64
    dims: [4585]
  }
]
output [
  {
    name: "atc7__0"
    data_type: TYPE_FP32
    dims: [990]
  },
  {
    name: "atc5__1"
    data_type: TYPE_FP32
    dims: [467]
  }
]

instance_group [ {
  count: 1
  kind: KIND_GPU
}]

version_policy { latest { num_versions: 1 } }

dynamic_batching {
  preferred_batch_size: [ 10 ]
  max_queue_delay_microseconds: 5000
}

**Expected behavior**
A clear and concise description of what you expected to happen."

Don't expected to see this error, and when re-load model it should not have any downtime as the document claimed: https://github.com/triton-inference-server/server/blob/main/docs/model_management.md#model-control-mode-explicit
https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_21-04.html#rel_21-04

**Comment by tanmayv25** [comment]
Looks like triton fails to get the blob_property from Azure blob_client [here](https://github.com/triton-inference-server/server/blob/r21.04/src/core/filesystem.cc#L917).
The description for the API is [here](https://github.com/Azure/azure-storage-cpplite/blob/44f649b6ce3d0a815e015bd50adbb70134434df1/include/blob/blob_client.h#L525).

To rule out whether the issue is not because of your container configuration or within Triton itself, can you try writing a simple client that calls the above API to get the blob_property? If you can obtain blob properties outside triton, then indeed this is a bug within Triton which must be fixed.

**Comment by tanmayv25** [comment]
Actually, you can use a slightly modified version of this sample to perform the above experiment.
https://github.com/Azure/azure-storage-cpplite/blob/master/sample/sample2.cpp

**Comment by tony-asus** [comment]
Hi @tanmayv25 
I've followed your suggestion and run a simple sample to connect to my azure storage container, and I can get blob property in my sample:

my sample code:

auto blobProperty = bc.get_blob_property(containerName, blobName);
assert(errno == 0);
std::cout << "Size of BLob: " << blobProperty.size << std::endl;
std::cout << "BLob last modified: " << blobProperty.last_modified << std::endl;
std::cout << "blob is valid: " << blobProperty.valid() << std::endl;

output:
Size of BLob: 490
BLob last modified: 1622793513
blob is valid: 1

**Comment by tanmayv25** [comment]
Thanks for your experiment! I am opening an issue with our dev team and will look into it soon. We might reach out to you in case any more information is needed.

**Comment by CoderHam** [comment]
@tony-asus did you run your same inside the Triton container?
Can you double check your credentials and the file path as://tonytesttritonaccount/tony-model-repository/some_model is valid?

It appears to be that the model repository path you passed is the path to a model and not the higher level model repository directory. Read about the model repository directory structure here: https://github.com/triton-inference-server/server/blob/main/docs/model_repository.md

**Comment by tony-asus** [comment]
@CoderHam I've found I gave the wrong information in my description, I indeed set **--model-repository=as://tonytesttritonaccount/tony-model-repository/** in my container, without specific model path. And I checked credential and file path in container are the same with my test sample.

**Comment by CoderHam** [comment]
@tony-asus I ran some tests with and without explicit model control on the latest master and it worked fine. 

Before I can confirm that the issue is fixed in the latest master, can you confirm that you set the AZURE_STORAGE_ACCOUNT environment variable?

**Comment by tony-asus** [comment]
@CoderHam yes, both AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY were set in the environment variables. I am using nvcr.io/nvidia/tritonserver:21.03-py3 image for the container now, and it doesn't have any error. 

I'm using explicit model control mode.

**Comment by CoderHam** [comment]
I zeroed in on what might be the cause but I believe this may be a bug in the azure sdk: https://github.com/triton-inference-server/server/commit/0a7e95222ec73503517ab3f9ae9429288ad12eec#diff-d3cefea3688bf98af36948db6dd24c6da989ca0db0c2b61fcc85240978efc27aR918-R923
This was the change that is causing Triton to think that your blob property cannot be gotten. Since the errno is 0 but the blob is not valid. 
Fixing the same and adding a test for explicit model control to our current azure storage test with https://github.com/triton-inference-server/server/pull/3002

Not sure why the property is not valid here when no error is reported.

**Comment by deadeyegoodwin** [comment]
Fixed with #3002

**Comment by evanlouie** [comment]
Still getting this error on `nvcr.io/nvidia/tritonserver:21.08-py3`, do not get it on `nvcr.io/nvidia/tritonserver:21.03-py3`.

Can confirm that the env vars expected `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_KEY` are set and that those values work properly with `21.03-py3`.

Any idea as to why this is still happening?
