### ISSUE TITLE
Triton Server build failed because DCGM 2.2.9 public key is not available

### ISSUE THREAD

**Issue by yaoyunda** [triton-inference-server/server#4306]
**Description**
The triton server build is previously successful, it starts to fail about a day ago.
Here is part of log:
Hit:2 https://apt.kitware.com/ubuntu focal InRelease
Err:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
[tritonserver_build.log](https://github.com/triton-inference-server/server/files/8588880/tritonserver_build.log)

I did some debugging for this failure. from the https://developer.nvidia.com/dcgm#Downloads
The current DCGM is 2.3 and the 2.2.9 is not shown anymore.

I cherry picked the code from build.py to install DCGM 2.2.9 in VM, it is also failed, and install 2.3 is successful.

**Triton Information**
What version of Triton are you using?
r22.03, r22.04
Are you using the Triton container or did you build it yourself?
build it by myself

**To Reproduce**
Steps to reproduce the behavior.

build tritonserver using optional features:
./build.py --cmake-dir=./build
-build-dir=/mnt/citritonbuild
--enable-logging
--enable-stats
--enable-tracing
--enable-metrics
--enable-gpu-metrics
--enable-gpu
--filesystem=azure_storage
--endpoint=http
--endpoint=grpc
--repo-tag=common:r22.03
--repo-tag=core:r22.03
--repo-tag=backend:r22.03
--repo-tag=thirdparty:r22.03
--backend=ensemble
--backend=identity:r22.03
--backend=repeat:r22.03
--backend=square:r22.03
--backend=onnxruntime:r22.03
--backend=python:r22.03
--repoagent=checksum:r22.03

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
build should be successful.

**Comment by CoderHam** [comment]
cc @jbkyang-nvi

**Comment by yaoyunda** [comment]
@CoderHam and @jbkyang-nvi , is  anyone looking this issue? and is there any quick fix? it is really a blocking issue.

**Comment by Tabrizian** [comment]
The issue has been fixed and merged to main. https://github.com/triton-inference-server/server/commit/270b9db032c96631c60957083766f4746c5d240b

**Comment by Hadrien-Cornier** [comment]
This fix does not work for me. 
I still get 
```
#8 6.758 E: Unable to locate package datacenter-gpu-manager
```

Here is what I did : 
```
git clone https://github.com/triton-inference-server/server.git && cd server && git checkout r22.04 && git cherry-pick 270b9db032c96631c60957083766f4746c5d240b --no-commit
```

```
cd server/ && python3 compose.py --enable-gpu --backend tensorflow2 --container-version 22.04 --output-name triton-slim:latest
```

System info : 
MacBook with a Chip Apple M1 Max

**Comment by Hadrien-Cornier** [comment]
I also tried replacing this line in the Dockerfile.compose that compose.py creates : 
```
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin &&     mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600 &&     apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub &&     add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /" &&     apt-get update && apt-get install -y datacenter-gpu-manager=1:2.2.9
```

with this line : 
```RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb && dpkg -i cuda-keyring_1.0-1_all.deb  && add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /" && apt-get update && apt-get install -y datacenter-gpu-manager
```

in order to match the newest instructions from [https://developer.nvidia.com/dcgm#Downloads](https://developer.nvidia.com/dcgm#Downloads), 

but this also results in the error : 

```
#8 6.758 E: Unable to locate package datacenter-gpu-manager
```

**Comment by jbkyang-nvi** [comment]
Since DCGM is Nvidia specific, I'm not sure if any GPU metrics can be found for you. 
 You can try removing the ` --enable-gpu-metrics` to disable DCGM installation.


By the way, Triton does not support M1 builds. However I think some people have managed to do CPU only builds though: https://github.com/triton-inference-server/server/issues/3980

**Comment by jbkyang-nvi** [comment]
@yaoyunda

I think the DCGM fix @Tabrizian  mentioned should fix your problem, if the VM has access to Nvidia GPUs.

**Comment by yaoyunda** [comment]
@jbkyang-nvi , Thanks.
I replaced public key in the files using DCGM fix @Tabrizian mentioned, it works now.

**Comment by jbkyang-nvi** [comment]
> Hi @jbkyang-nvi, I was able to build the container with my same code above on a machine with ubuntu and no Nvidia gpu. (I was trying to do a build on MacOS but execute it later on a Linux server) Thanks

@Hadrien-Cornier can you remove the metrics/gpu related flags in your build script?

**Comment by nv-kmcgill53** [comment]
This fix will be available in 22.05

**Comment by dyastremsky** [comment]
22.05 was just released! https://github.com/triton-inference-server/server/releases/tag/v2.22.0

Closing issue due to lack of activity. Please re-open the issue if you would like to follow up with this issue.
